export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT = 'LOGOUT';

export const TASKS = {
  CREATE: 'TASKS_CREATE',
  GET_ALL: 'TASKS_GET_ALL',
  REMOVE: 'TASKS_REMOVE',
  UPDATE: 'TASKS_UPDATE',
}

export const CATEGORIES = {
  CREATE: 'CATEGORIES_CREATE',
  GET_ALL: 'CATEGORIES_GET_ALL',
  REMOVE: 'CATEGORIES_REMOVE',
  UPDATE: 'CATEGORIES_UPDATE',
}
